      - name: Build RustDesk upstream core
        shell: bash
        run: |
          set -e

          ./build.py \
            --flutter \
            --hwcodec \
            --unix-file-copy-paste \
            ${{ matrix.extra_args }}

          echo "===== Build products ====="
          ls -lah flutter/build/macos/Build/Products/Release/

          test -d \
            flutter/build/macos/Build/Products/Release/RustDesk.app
