name: SMDesk macOS

on:
  workflow_dispatch:
  push:
    branches:
      - smdesk-1.2

permissions:
  contents: read

env:
  SMDESK_VERSION: "1.2.1"
  FLUTTER_VERSION: "3.24.5"
  MAC_RUST_VERSION: "1.81"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-macos:
    name: SMDesk macOS ${{ matrix.arch }}
